# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-24 17:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_floor', models.BooleanField()),
                ('last_floor', models.BooleanField()),
                ('area', models.IntegerField(default=40)),
                ('price', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_dstr', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Floor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_no', models.IntegerField(default=0)),
                ('to_no', models.IntegerField(default=3)),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_mtrl', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='apartment',
            name='ap_floor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ApartmentPrices.Floor'),
        ),
        migrations.AddField(
            model_name='apartment',
            name='h_dstr',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ApartmentPrices.District'),
        ),
        migrations.AddField(
            model_name='apartment',
            name='h_mtrl',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ApartmentPrices.Material'),
        ),
        migrations.AddField(
            model_name='apartment',
            name='room_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ApartmentPrices.Room'),
        ),
    ]
