# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-24 18:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ApartmentPrices', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apartment',
            options={'verbose_name': 'Квартира', 'verbose_name_plural': 'Квартира'},
        ),
        migrations.AlterModelOptions(
            name='district',
            options={'verbose_name': 'Район', 'verbose_name_plural': 'Район'},
        ),
        migrations.AlterModelOptions(
            name='floor',
            options={'verbose_name': 'Этаж', 'verbose_name_plural': 'Этаж'},
        ),
        migrations.AlterModelOptions(
            name='material',
            options={'verbose_name': 'Материал дома', 'verbose_name_plural': 'Материал дома'},
        ),
        migrations.AlterModelOptions(
            name='room',
            options={'verbose_name': 'Количество комнат', 'verbose_name_plural': 'Количество комнат'},
        ),
        migrations.AddField(
            model_name='apartment',
            name='total_floors',
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='ap_floor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ApartmentPrices.Floor', verbose_name='Этаж'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='h_dstr',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ApartmentPrices.District', verbose_name='Район'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='h_mtrl',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ApartmentPrices.Material', verbose_name='Материал дома'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='room_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ApartmentPrices.Room', verbose_name='Количество комнат'),
        ),
    ]
