# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-24 19:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApartmentPrices', '0002_auto_20180425_0212'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='balcony',
            field=models.BooleanField(default=False, verbose_name='Есть балкон?'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='area',
            field=models.FloatField(verbose_name='Площадь квартиры'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='first_floor',
            field=models.BooleanField(verbose_name='На первом этаже?'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='last_floor',
            field=models.BooleanField(verbose_name='На последнем этаже?'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='price',
            field=models.FloatField(verbose_name='Стоимость квартиры'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='total_floors',
            field=models.IntegerField(default=5, verbose_name='Всего этажей в доме'),
        ),
    ]
