# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-25 11:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApartmentPrices', '0003_auto_20180425_0336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='total_floors',
            field=models.IntegerField(default=5, verbose_name='Всего этажей'),
        ),
    ]
