# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-25 16:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApartmentPrices', '0004_auto_20180425_1909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='first_floor',
            field=models.BooleanField(verbose_name='На 1-м этаже?'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='price',
            field=models.FloatField(verbose_name='Стоимость'),
        ),
    ]
