# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-07 02:23
from __future__ import unicode_literals

import ApartmentPrices.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApartmentPrices', '0006_auto_20180506_0051'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apartment',
            name='ap_floor',
        ),
        migrations.AddField(
            model_name='apartment',
            name='total_floors',
            field=models.PositiveIntegerField(default=5, validators=[django.core.validators.MaxValueValidator(100), ApartmentPrices.models.validate_nonzero]),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='room_no',
            field=models.PositiveIntegerField(default=2, validators=[django.core.validators.MaxValueValidator(20), ApartmentPrices.models.validate_nonzero]),
        ),
        migrations.DeleteModel(
            name='Floor',
        ),
        migrations.DeleteModel(
            name='Room',
        ),
    ]
