# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-08 18:47
from __future__ import unicode_literals

import ApartmentPrices.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApartmentPrices', '0007_auto_20180507_1023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='room_no',
            field=models.PositiveIntegerField(default=2, validators=[django.core.validators.MaxValueValidator(20), ApartmentPrices.models.validate_nonzero], verbose_name='Количество комнат'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='total_floors',
            field=models.PositiveIntegerField(default=5, validators=[django.core.validators.MaxValueValidator(100), ApartmentPrices.models.validate_nonzero], verbose_name='Всего этажей'),
        ),
    ]
