# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-08 20:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ApartmentPrices', '0008_auto_20180509_0247'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apartment',
            name='price',
        ),
    ]
